FROM golang:1.25.3-bookworm as Develop

# 作業ディレクトリを設定
WORKDIR /app/src

# 依存関係をインストール
RUN apt update \
    && apt install -y wget curl git

# air をインストール 
RUN go install github.com/air-verse/air@latest

CMD [ "air","-c","./.air.toml" ]

# Start by building the application.
FROM golang:1.25.3 as build

WORKDIR /go/src/app
COPY ./src .

RUN go mod download
RUN CGO_ENABLED=0 go build -o /go/bin/app

# Now copy it into our base image.
FROM gcr.io/distroless/static-debian12 as release
COPY --from=build /go/bin/app /
CMD ["/app"]